### ISSUE TITLE
数据库表结构执行model.py报错

### ISSUE THREAD

**Issue by nondevops** [zhxfei/easy-admin#1]

**Comment by nondevops** [comment]
手动创建admin数据库，把model.py移动到manag.py下执行，结果如下：
![image](https://user-images.githubusercontent.com/12181410/45308568-4f78d780-b554-11e8-9742-3114f8d9e998.png)
python3.6.5

**Comment by zhxfei** [comment]
这是没有表的报错，第一次运行需要把modles最下面的代码块的注释给去掉，去初始化数据库
